services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: userService
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d userService -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  userservice:
    build: ./userService
    container_name: user-service
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy

  postservice:
    build: ./postService
    container_name: post-service
    ports:
      - "50051:50051"
    depends_on:
      db:
        condition: service_healthy

  apigateway:
    build: ./apiGateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - userservice

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


volumes:
  postgres_data: