services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: social_network
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d social_network -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  userservice:
    build: ./userService
    container_name: user-service
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy

  postservice:
    build: ./postService
    container_name: post-service
    ports:
      - "50051:50051"
    depends_on:
      db:
        condition: service_healthy

  apigateway:
    build: ./apiGateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - userservice

volumes:
  postgres_data: