FROM python:3.11

WORKDIR /app

COPY ./apiGateway/requirements.txt .

RUN pip install -r requirements.txt

COPY ./proto ./proto
COPY ./apiGateway ./apiGateway

RUN python -m grpc_tools.protoc \
    --proto_path=proto \
    --python_out=proto \
    proto/post.proto

CMD ["uvicorn", "apiGateway.app.main:app", "--host", "0.0.0.0", "--port", "8000"]