FROM python:3.11

WORKDIR /app

COPY ./postService/requirements.txt .

RUN pip install -r requirements.txt

COPY ./proto ./proto
COPY ./postService ./postService

RUN python -m grpc_tools.protoc \
    --proto_path=proto \
    --python_out=proto \
    proto/post.proto

CMD ["python", "-m", "postService.app.main"]