FROM python:3.9

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
RUN python -m grpc_tools.protoc -I./app --python_out=app --grpc_python_out=app app/service.proto

CMD ["python", "app/main.py"]