FROM python:3.11

WORKDIR /app

COPY ./statService/requirements.txt .
RUN pip install -r requirements.txt

COPY ./proto ./proto
COPY ./statService ./statService

RUN python -m grpc_tools.protoc \
    --proto_path=proto \
    --python_out=proto \
    --grpc_python_out=proto \
    proto/stat.proto

CMD ["python", "-m", "statService.app.main"]
