erDiagram
    POSTS {
        int post_id PK
        int user_id
        string post_name
        string content
        datetime created_at
        datetime updated_at
    }
    COMMENTS {
        int id PK
        int post_id FK
        int user_id
        string content
        datetime created_at
        datetime updated_at
        int parent_comment_id FK
        boolean is_deleted
    }
    LIKES {
        int post_id PK
        int user_id PK
        datetime created_at
    }
    POST_ATTACHMENTS {
        int id PK
        int post_id FK
        string attachment_url
        string attachment_type
        datetime uploaded_at
    }

    POSTS ||--o{ POST_ATTACHMENTS : "содержит"
    POSTS ||--o{ COMMENTS : "содержит"
    POSTS ||--o{ LIKES : "получает"
    COMMENTS ||--|{ COMMENTS : "ответ на"
